
export const UPDATE_FILTER = 'UPDATE_FILTER';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UPDATE_BRANDS = 'UPDATE_BRANDS';
export const UPDATE_RANGES = 'UPDATE_RANGES';
export const UPDATE_COLORS = 'UPDATE_COLORS';
export const UPDATE_CART = 'UPDATE_CART';
export const UPDATE_GOODS = 'UPDATE_GOODS';
export const UPDATE_CART_COUNTER = 'UPDATE_CART_COUNTER';
export const DELETE_ITEM_FROM_CART = 'DELETE_ITEM_FROM_CART';
export const UPDATE_LOADING = 'UPDATE_LOADING';
